#!/bin/sh
set -u # don't allow uninitialized variables
set -e # exit on any error

echo jammit...
heroku jammit:add

echo pushing to origin (github)
git push origin master 

echo pushing heroku
git push heroku master
