#!/bin/sh
DIR_NAME=`dirname $0`
OUT_DIR=$DIR_NAME/../tmp
OUT_FILE=$OUT_DIR/out.txt
echo $DIR_NAME  $OUT_FILE $1
CF_DATADIR=$DIR_NAME LD_LIBRARY_PATH=$DIR_NAME $DIR_NAME/cuneiform $1 -o $OUT_FILE
echo after
cat $OUT_FILE
rm $OUT_FILE
